### ISSUE TITLE
Steps in Readme about how to scan a container image 

### ISSUE THREAD

**Issue by rmkanda** [openbridge/clamav#11]
The Readme has steps to run clamav as container

```
docker pull openbridge/clamav
docker run -d -p 3310:3310 openbridge/clamav
```

But it doesn't include steps to scan a docker image in the host using the clamav.
@tspicer Can you help?

**Comment by tspicer** [comment]
It is not intended for the use case you are describing. You can mount shared volumes, use the Clam API to send files for review, but if you are asking this container to have access to another container outside of typically shared systems, it will not work. You might just want to install it locally in your container.
