### ISSUE TITLE
Changes to etc/clamd.conf are overwritten by image

### ISSUE THREAD

**Issue by mbordash** [openbridge/clamav#12]
**Describe the bug**
When you make a change to the config /etc/clamd.conf and rebuild the container, the changes are overwritten by the docker-compose build process

**To Reproduce**
1. Make a change to clamd.conf
2. run docker-compose up --build --force-recreate
3. Login to the container and notice the changes are not present

**Expected behavior**
I expect changes to the clamd.conf to be respected during docker build process

**Screenshots**

**Desktop (please complete the following information):**
Docker for Mac

**Comment by tspicer** [comment]
@mbordash, curious why you are trying to edit the file in advance of a build. Why not simply mount a user-defined config in the path via `volume` ? Also, how are you editing the file?  Are you editing the file in the `/etc` directory?

**Comment by mbordash** [comment]
Yes this is a great way. What led me to post an issue was that the default entrypoint script was setting the wrong IP address in  Docker for Mac, and I was just going to edit the conf file before copying over to the container with the proper hostname for our bridge network. Thanks for your rapid reply!

**Comment by tspicer** [comment]
Did a fresh build `docker build -t openbridge/clamav .`

Ran build `docker run -d -p 3310:3310 openbridge/clamav`

Check config `docker exec -it 901c8a4ddf5c cat /etc/clamd.conf`

Got this output
```

LogSyslog yes
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.sock
FixStaleSocket true
LocalSocketGroup clamav
LocalSocketMode 666
TemporaryDirectory /tmp
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 172.17.0.1
MaxConnectionQueueLength 200
MaxThreads 10
ReadTimeout 400
Foreground true

HeuristicScanPrecedence yes
StructuredDataDetection no
#StructuredSSNFormatNormal yes
ScanPE yes
ScanELF yes
#DetectBrokenExecutables yes
ScanOLE2 yes
ScanPDF yes
ScanSWF yes
ScanMail yes
PhishingSignatures yes
PhishingScanURLs yes

ScanArchive yes

ArchiveBlockEncrypted no

MaxScanSize 1000M
MaxFileSize 1000M
StreamMaxLength 1000M

Bytecode yes
BytecodeSecurity TrustSigned
BytecodeTimeout 240000
```

Changed config by adding `#FOOOOOOOOOO` at the top of the file in `/etc/clamd.conf`

Repeat build and run process, check again `docker exec -it 6ff8eb1928e8 cat /etc/clamd.conf` and change is present.

```
#FOOOOOOOOOO
LogSyslog yes
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.sock
FixStaleSocket true
LocalSocketGroup clamav
LocalSocketMode 666
TemporaryDirectory /tmp
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 172.17.0.1
MaxConnectionQueueLength 200
MaxThreads 10
ReadTimeout 400
Foreground true

HeuristicScanPrecedence yes
StructuredDataDetection no
#StructuredSSNFormatNormal yes
ScanPE yes
ScanELF yes
#DetectBrokenExecutables yes
ScanOLE2 yes
ScanPDF yes
ScanSWF yes
ScanMail yes
PhishingSignatures yes
PhishingScanURLs yes

ScanArchive yes

ArchiveBlockEncrypted no

MaxScanSize 1000M
MaxFileSize 1000M
StreamMaxLength 1000M

Bytecode yes
BytecodeSecurity TrustSigned
BytecodeTimeout 240000
```

Next, I did this, change the `/etc/clamd.conf` again to be `#99999999999999`

The run `docker-compose up -d --build --force-recreate`

Then check the file `docker exec -it d5481baf3bfb cat /etc/clamd.conf`
```
#99999999999999
LogSyslog yes
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.sock
FixStaleSocket true
LocalSocketGroup clamav
LocalSocketMode 666
TemporaryDirectory /tmp
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 172.24.0.1
MaxConnectionQueueLength 200
MaxThreads 10
ReadTimeout 400
Foreground true

HeuristicScanPrecedence yes
StructuredDataDetection no
#StructuredSSNFormatNormal yes
ScanPE yes
ScanELF yes
#DetectBrokenExecutables yes
ScanOLE2 yes
ScanPDF yes
ScanSWF yes
ScanMail yes
PhishingSignatures yes
PhishingScanURLs yes

ScanArchive yes

ArchiveBlockEncrypted no

MaxScanSize 1000M
MaxFileSize 1000M
StreamMaxLength 1000M

Bytecode yes
BytecodeSecurity TrustSigned
BytecodeTimeout 240000
```

@mbordash, having trouble understanding the issue. What am I missing? Thanks!

**Comment by tspicer** [comment]
Thanks for the clarification. Would it be better to simply pass the IP as an`ENV` variable?

**Comment by mbordash** [comment]
I think that would work well.  My colleague and I are digging deeper as to why we have difference between our docker on mac vs docker for linux.  I think the issue we're having has nothing to do with your fantastic repo.  Sorry for the distraction, and thank you for your help!!
