### ISSUE TITLE
LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav

### ISSUE THREAD

**Issue by thearchduke** [openbridge/clamav#19]
**Describe the bug**
When I follow the instructions, the container fails to start, with the error `LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav`. Longer trace below.

**To Reproduce**
1. `docker pull openbridge/clamav`
2. `docker run -d -p 3310:3310 openbridge/clamav:latest`
3. Get the ID from `docker ps -a`, check `docker logs`:

```
+ run
+ mode
+ LOCALIPV4=0.0.0.0
+ PUBLICIPV4=0.0.0.0
+ export PUBLICIPV4
+ export LOCALIPV4
+ echo PUBLICIPV4=0.0.0.0
+ echo LOCALIPV4=0.0.0.0
+ sed -i 's|{{LOCALIPV4}}|0.0.0.0|g' /etc/clamd.conf
+ sed -i 's|{{PUBLICIPV4}}|0.0.0.0|g' /etc/clamd.conf
+ freshclam
+ chown -R clamav:clamav /var/lib/clamav/
++ find /var/lib/clamav/daily.cvd -mtime +2 -print
find: ‘/var/lib/clamav/daily.cvd’: No such file or directory
+ [[ -n '' ]]
+ [[ ! -f /var/lib/clamav/daily.cvd ]]
+ echo 'Clamd files are too old. Updating...'
+ echo 'OK: Running freshclam to update virus databases. This can take a few minutes...'
+ sleep 1
Clamd files are too old. Updating...
OK: Running freshclam to update virus databases. This can take a few minutes...
+ run='freshclam -d -c 12 -p /run/freshclam.pid'
+ bash -c 'freshclam -d -c 12 -p /run/freshclam.pid'
+ crond
+ CRONFILE=/crontab.conf
+ CRON_M=28
+ CRON_H=4
+ [[ -f /crontab.conf ]]
+ echo SHELL=/bin/bash
+ echo PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ echo '{{CRON_M}} {{CRON_H}} * * * /usr/bin/env bash -c freshclam' '--quiet 2>&1'
+ tee /crontab.conf
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
{{CRON_M}} {{CRON_H}} * * * /usr/bin/env bash -c freshclam --quiet 2>&1
+ sed -i 's|{{CRON_H}}|4|g' /crontab.conf
+ sed -i 's|{{CRON_M}}|28|g' /crontab.conf
+ cat /crontab.conf
+ crontab -
+ crontab -l
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
28 4 * * * /usr/bin/env bash -c freshclam --quiet 2>&1
+ runcrond='crond -b'
+ bash -c 'crond -b'
+ monit
+ echo 'set daemon 15'
+ echo '   with START DELAY 30'
+ echo 'set pidfile /var/run/monit.pid'
+ echo 'set statefile /var/run/monit.state'
+ echo 'set httpd port 2849 and'
+ echo '   use address localhost'
+ echo '   allow localhost'
+ echo 'set logfile syslog'
+ echo 'set eventqueue'
+ echo '   basedir /var/run'
+ echo '   slots 100'
+ echo 'include /etc/monit.d/*'
+ tee /etc/monitrc
set daemon 15
   with START DELAY 30
set pidfile /var/run/monit.pid
set statefile /var/run/monit.state
set httpd port 2849 and
   use address localhost
   allow localhost
set logfile syslog
set eventqueue
   basedir /var/run
   slots 100
include /etc/monit.d/*
+ find /etc/monit.d -maxdepth 5 -type f -exec sed -i -e 's|{{LOCALIPV4}}|0.0.0.0|g' '{}' ';'
+ find /etc/monit.d -maxdepth 5 -type f -exec sed -i -e 's|{{PUBLICIPV4}}|0.0.0.0|g' '{}' ';'
+ chmod 700 /etc/monitrc
+ run='monit -c /etc/monitrc'
+ bash -c 'monit -c /etc/monitrc'
 New Monit id: fa807ae58b7cece2b492c9aa4642ed70
 Stored in '/root/.monit.id'
Starting Monit 5.27.2 daemon with http interface at [localhost]:2849
+ echo 'OK: All processes have completed. Service is ready...'
OK: All processes have completed. Service is ready...
+ exec /usr/sbin/clamd -c /etc/clamd.conf
LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
ERROR: Can't open file or directory
```

**Expected behavior**
Last week, this ran fine, exposing the service on port 3310.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Comment by tspicer** [comment]
Rather than pull, can you build?

**Comment by thearchduke** [comment]
I get the same error. It's possible I'm doing something wrong.

```
[pull this repo]
docker build -t openbridge/clamav:built .
docker run -d -p 3310:3310 openbridge/clamav:built
.....
LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
```

**Comment by tspicer** [comment]
Nope, it was on me. I just pushed another fix to care for this use case. Try again if you can. Also, try using docker compose `docker-compose up -d`

**Comment by thearchduke** [comment]
Awesome, thanks! This now works with both `docker run` and `docker-compose`.

**Comment by bboyadao** [comment]
build make sense. 
`
clamav  | + find /etc/monit.d -maxdepth 5 -type f -exec sed -i -e 's|{{LOCALIPV4}}|0.0.0.0|g' '{}' ';'
clamav  | + find /etc/monit.d -maxdepth 5 -type f -exec sed -i -e 's|{{PUBLICIPV4}}|0.0.0.0|g' '{}' ';'
clamav  | + chmod 700 /etc/monitrc
clamav  | + run='monit -c /etc/monitrc'
clamav  | + bash -c 'monit -c /etc/monitrc'
clamav  |  New Monit id: 401ac8782491dbbaaa2cb23146d9f3bf
clamav  |  Stored in '/root/.monit.id'
clamav  | Starting Monit 5.27.2 daemon with http interface at [localhost]:2849
clamav  | + echo 'OK: All processes have completed. Service is ready...'
clamav  | OK: All processes have completed. Service is ready...
clamav  | + exec /usr/sbin/clamd -c /etc/clamd.conf
clamav  | LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
clamav  | ERROR: Can't open file or directory
clamav exited with code 1

`
i have to use image on dockerhub instead .

**Comment by tspicer** [comment]
I just did a pull and ran `docker run -d -p 3310:3310 openbridge/clamav` without incident.

**Comment by bboyadao** [comment]
i found a problem. that i move up docker-compose.yml 1 folder level to fit my existed project. it's not work even i manual build or using image.
<img width="314" alt="Screen Shot 2021-08-04 at 02 19 44" src="https://user-images.githubusercontent.com/25122065/128073512-47f32aa5-7a6e-49a0-b8a9-4f0ca9383072.png">

**Comment by tspicer** [comment]
I really do not have a sense of your issue as I have run it without issue. This sounds like a local ENV issue.

**Comment by bboyadao** [comment]
<img width="1004" alt="Screen Shot 2021-08-04 at 02 25 31" src="https://user-images.githubusercontent.com/25122065/128074186-2d798e02-6489-4444-a19c-4d217a31c987.png">

`╰─❯ dc up --build                                                                                                                                                        ─╯
[+] Running 1/0
 ⠿ Container clamav  Created                                                                                                                                           0.0s
Attaching to clamav
clamav  | + run
clamav  | + mode
clamav  | + LOCALIPV4=0.0.0.0
clamav  | + PUBLICIPV4=0.0.0.0
clamav  | + export PUBLICIPV4
clamav  | + export LOCALIPV4
clamav  | + echo PUBLICIPV4=0.0.0.0
clamav  | + echo LOCALIPV4=0.0.0.0
clamav  | + sed -i 's|{{LOCALIPV4}}|0.0.0.0|g' /etc/clamd.conf
clamav  | + sed -i 's|{{PUBLICIPV4}}|0.0.0.0|g' /etc/clamd.conf
clamav  | + freshclam
clamav  | + chown -R clamav:clamav /var/lib/clamav/
clamav  | ++ find /var/lib/clamav/daily.cvd -mtime +2 -print
clamav  | find: ‘/var/lib/clamav/daily.cvd’: No such file or directory
clamav  | + [[ -n '' ]]
clamav  | + [[ ! -f /var/lib/clamav/daily.cvd ]]
clamav  | + echo 'Clamd files are too old. Updating...'
clamav  | Clamd files are too old. Updating...
clamav  | + echo 'OK: Running freshclam to update virus databases. This can take a few minutes...'
clamav  | OK: Running freshclam to update virus databases. This can take a few minutes...
clamav  | + sleep 1
clamav  | + run='/usr/bin/freshclam -p /run/freshclam.pid'
clamav  | + bash -c '/usr/bin/freshclam -p /run/freshclam.pid'
clamav  | ClamAV update process started at Tue Aug  3 19:25:48 2021
clamav  | WARNING: Your ClamAV installation is OUTDATED!
clamav  | WARNING: Local version: 0.103.1 Recommended version: 0.103.3
clamav  | DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
clamav  | daily database available for download (remote version: 26252)
clamav  | WARNING: Download failed (6) WARNING:  Message: Couldn't resolve host name
clamav  | WARNING: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
clamav  | Trying again in 5 secs...
clamav  | daily database available for download (remote version: 26252)
clamav  | WARNING: Download failed (6) WARNING:  Message: Couldn't resolve host name
clamav  | WARNING: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
clamav  | Trying again in 5 secs...
clamav  | daily database available for download (remote version: 26252)
clamav  | ERROR: Download failed (6) ERROR:  Message: Couldn't resolve host name
clamav  | ERROR: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
clamav  | Giving up on https://database.clamav.net...
clamav  | ERROR: Update failed for database: daily
clamav  | WARNING: fc_update_databases: fc_update_database failed: Connection failed (5)
clamav  | ERROR: Database update process failed: Connection failed (5)
clamav  | ERROR: Update failed.
clamav  | + crond
clamav  | + CRONFILE=/crontab.conf
clamav  | + CRON_M=58
clamav  | + CRON_H=3
clamav  | + [[ -f /crontab.conf ]]
clamav  | + echo 'OK: CRONFILE is present. Configuring crontab with settings in /crontab.conf...'
clamav  | OK: CRONFILE is present. Configuring crontab with settings in /crontab.conf...
clamav  | + sed -i 's|{{CRON_H}}|3|g' /crontab.conf
clamav  | + sed -i 's|{{CRON_M}}|58|g' /crontab.conf
clamav  | + cat /crontab.conf
clamav  | + crontab -
clamav  | + crontab -l
clamav  | SHELL=/bin/bash
clamav  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
clamav  | 28 4 * * * /usr/bin/env bash -c freshclam --quiet 2>&1
clamav  | + runcrond='crond -b'
clamav  | + bash -c 'crond -b'
clamav  | crond[20]: crond (busybox 1.32.1) started, log level 8
clamav  | + monit
clamav  | + echo 'set daemon 15'
clamav  | + echo '   with START DELAY 30'
clamav  | + echo 'set pidfile /var/run/monit.pid'
clamav  | + echo 'set statefile /var/run/monit.state'
clamav  | + echo 'set httpd port 2849 and'
clamav  | + echo '   use address localhost'
clamav  | + + echo '   allow localhost'
clamav  | tee /etc/monitrc
clamav  | + echo 'set logfile syslog'
clamav  | + echo 'set eventqueue'
clamav  | + echo '   basedir /var/run'
clamav  | + echo '   slots 100'
clamav  | + echo 'include /etc/monit.d/*'
clamav  | set daemon 15
clamav  |    with START DELAY 30
clamav  | set pidfile /var/run/monit.pid
clamav  | set statefile /var/run/monit.state
clamav  | set httpd port 2849 and
clamav  |    use address localhost
clamav  |    allow localhost
clamav  | set logfile syslog
clamav  | set eventqueue
clamav  |    basedir /var/run
clamav  |    slots 100
clamav  | include /etc/monit.d/*
clamav  | + find /etc/monit.d -maxdepth 5 -type f -exec sed -i -e 's|{{LOCALIPV4}}|0.0.0.0|g' '{}' ';'
clamav  | + find /etc/monit.d -maxdepth 5 -type f -exec sed -i -e 's|{{PUBLICIPV4}}|0.0.0.0|g' '{}' ';'
clamav  | + chmod 700 /etc/monitrc
clamav  | + run='monit -c /etc/monitrc'
clamav  | + bash -c 'monit -c /etc/monitrc'
clamav  | Starting Monit 5.27.2 daemon with http interface at [localhost]:2849
clamav  | + echo 'OK: All processes have completed. Service is ready...'
clamav  | OK: All processes have completed. Service is ready...
clamav  | + exec /usr/sbin/clamd -c /etc/clamd.conf
clamav  | LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
clamav  | ERROR: Can't open file or directory
clamav exited with code 1

╭─   ~/Projects/docker ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  17s  02:25:59 ─╮
╰─❯                                                                                                                                                                      ─╯
`
that how it's broke.

**Comment by tspicer** [comment]
Looks like you need to dig into the error `clamav | LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav`. I think that is telling you there is an issue with your local ENV. Feel free to edit this to something other than a volume.

**Comment by bboyadao** [comment]
> I just did a pull and ran `docker run -d -p 3310:3310 openbridge/clamav` without incident.

ah yes thank you so much. i used -f <docker-file> with docker compose (new update) not docker-compose.

**Comment by tspicer** [comment]
Did you look at the logs you posted? Your errors are pretty clear. 

```
clamav | DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
clamav | daily database available for download (remote version: 26252)
clamav | WARNING: Download failed (6) WARNING: Message: Couldn't resolve host name
clamav | WARNING: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
clamav | Trying again in 5 secs...
clamav | daily database available for download (remote version: 26252)
clamav | WARNING: Download failed (6) WARNING: Message: Couldn't resolve host name
clamav | WARNING: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
clamav | Trying again in 5 secs...
clamav | daily database available for download (remote version: 26252)
clamav | ERROR: Download failed (6) ERROR: Message: Couldn't resolve host name
clamav | ERROR: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
clamav | Giving up on https://database.clamav.net...
clamav | ERROR: Update failed for database: daily
clamav | WARNING: fc_update_databases: fc_update_database failed: Connection failed (5)
clamav | ERROR: Database update process failed: Connection failed (5)
clamav | ERROR: Update failed.
```

**Comment by bboyadao** [comment]
yes but container exit after that.
i fixed that by using old command `docker-compose -f docker-compose.yml` instead of my shell alias `dc (docker compose) -f ...`

**Comment by bboyadao** [comment]
sorry for this inconvenience. that's awsome.
