### ISSUE TITLE
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

### ISSUE THREAD

**Issue by NikolaIvc** [openbridge/clamav#20]
After performing test on K6 against API endpoint that calls clam docker container (through ClamClient) I got that last 50 requests failed (50 of 200) with the error message from above. K6 ran load test using 10 virtual users in this case.
Test was performed against Azure Function. 

Does this mean that there is some limitation on server/docker side or rather that TCPClient is not dealing well with sockets? Should I set something differently?

**Comment by tspicer** [comment]
Have you explored optimizing the config for your use case? http://manpages.ubuntu.com/manpages/bionic/man5/clamd.conf.5.html

Have you done any TCP optimization for Docker? 
https://docs.docker.com/get-started/overview/

How about the host system? Any optmnizations?

Are you hitting a single instance or have you planned for a cluster of instances behind a load balancer? 

I don't really have much other feedback as most of this is config or architecture-related, not the docker image.

**Comment by NikolaIvc** [comment]
Setting _MaxConnectionQueueLength NUMBER_ to 50 and _MaxThreads_ to 2 (in clamd.conf) helped me to get tests without any failure (500 error with message from the subject). I even tried test with 40 concurrent users who fired 2875 requests and everything went well.
